#!/bin/bash

cli_help() {
  cli_name=${0##*/}
  echo "$cli_name 0.1.0
A bash script performing port scan followed by aggressive scan using nmap.
Scan results will be produced in the current directory.
Developed by: Otsute

Usage: $cli_name [TARGET_IP]"
  exit 1
}


[ -z "$1" ] && cli_help

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then

  ip=$1

  echo -e "\n-------------------------"
  echo "Port scans"
  echo -e "-------------------------\n"

  echo "Executing: sudo nmap -v -p- -T4 -Pn -oG $ip-ports-scan $ip"
  sudo nmap -v -T4 --open -p- -Pn -oG $ip-ports-scan $ip 

  echo -e "\n-----------------------------------------------"
  echo "Service and Default Script scans on open ports"
  echo -e "-----------------------------------------------\n"

  echo "Extracting open ports from previous scan"
  ports=$(cat $ip-ports-scan | grep "Ports:" | grep -Eo '[0-9]{1,5}/' | grep -Eo '[0-9]{1,5}' | sed -z 's/\n/,/g;s/,$/\n/')
  echo "Executing: sudo nmap -sV -sC -v -Pn -oN $ip-service-script-scan -p $ports $ip"
  sudo nmap -v -sV -sC -Pn -oN $ip-agressive-scan -p $ports $ip
 
