#!/bin/bash

cli_help() {
  cli_name=${0##*/}
  echo "$cli_name 0.1.0
A bash script performing port scan followed by version and script scan using nmap.
Scan results will be produced in the current directory.
Developed by: Otsute

Usage: $cli_name [TARGET_IP]"
  exit 1
}


[ -z "$1" ] && cli_help

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then

  ip=$1

  echo -e "\n-------------------------"
  echo "Port scans"
  echo -e "-------------------------\n"

  echo "Executing: sudo nmap -p- -T4 -oG $ip-ports-scan $ip"
  sudo nmap -T4 --open -p- -oG -Pn $ip-ports-scan $ip 

  echo -e "\n-----------------------------------------------"
  echo "Service and Default Script scans on open ports"
  echo -e "-----------------------------------------------\n"

  echo "Extracting open ports from previous scan"
  ports=$(cat $ip-ports-scan | grep "Ports:" | grep -Eo '[0-9]{1,5}/' | grep -Eo '[0-9]{1,5}' | sed -z 's/\n/,/g;s/,$/\n/')
  echo "Executing: sudo nmap -sV -sC -oN $ip-service-script-scan -p $ports $ip"
  sudo nmap -sV -sC -oN -Pn $ip-service-script-scan -p $ports $ip

  if [[ $ports == *"80"* ]]; then
    echo -e "\n-----------------------------------------------"
    echo "port 80 detected"
    echo "Using Gobuster to brute force directory"
    echo -e "-----------------------------------------------\n"
    gobuster dir -u http://$ip -w /usr/share/wordlists/dirb/common.txt
  fi
else 
  echo "Not a valid ip address!"
fi
 
